### PR TITLE
Conversion from Sesame to RDF4J

### PR DESCRIPTION
**Pull request by ansell**
Convert from Sesame to RDF4J, fix some deprecations in the maven plugin, and make it possible to run sesame-vocab-builder from other working directories.

Signed-off-by: Peter Ansell p_ansell@yahoo.com

### CODE REVIEW

**Comment by ansell** [comment]
The support for Semargl has been temporarily commented out of the pom.xml files until a new Semargl release is available. Pull request for Semargl is at:

https://github.com/levkhomich/semargl/pull/45

**Comment by tkurz** [comment]
Cool Peter. Thx for the update.

**Comment by tkurz** [comment]
@ja-fra

**Comment by ansell** [comment]
Did you accidentally close this?

**Comment by tkurz** [comment]
Sorry. Yes, this was a mistake. @ja-fra if you are fine, we can merge this.

**Comment by ja-fra** [comment]
Ok, I'll check when I'm back from my vacation.

Thomas Kurz notifications@github.com schrieb am Fr., 05.08.2016, 8:18:

**Pull request closed without merging**
